name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lintowanie kodu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ustaw Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Instalacja zależności
        run: npm ci
      - name: Lintowanie kodu
        run: npm run lint

  unit-tests:
    name: Testy jednostkowe
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ustaw Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Instalacja zależności
        run: npm ci
      - name: Uruchom testy jednostkowe z coverage
        run: npm run test:coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage

  deploy-to-vercel:
    name: Wdrożenie na Vercel
    needs: unit-tests
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Ustaw Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
