name: Pull Request

on:
  pull_request:
    branches:
      - main
  push: # Dodaj to żeby testować
    branches:
      - main

jobs:
  lint:
    name: Lintowanie kodu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ustaw Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Instalacja zależności
        run: npm ci
      - name: Lintowanie kodu
        run: npm run lint

  unit-tests:
    name: Testy jednostkowe
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ustaw Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Instalacja zależności
        run: npm ci
      - name: Uruchom testy jednostkowe z coverage
        run: npm run test:coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage

  e2e-tests:
    name: Testy end-to-end
    needs: lint
    runs-on: ubuntu-latest
    environment: integration
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      E2E_EMAIL: ${{ secrets.E2E_EMAIL }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Ustaw Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Instalacja zależności
        run: npm ci
      - name: Instalacja Playwright i zależności systemowych
        run: npx playwright install --with-deps
      - name: Stwórz użytkownika testowego
        run: npm run setup:test-user
      - name: Uruchom testy e2e
        run: npm run test:e2e
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Upload coverage report e2e
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-coverage
          path: coverage

  status-comment:
    name: Komentarz statusu PR
    needs:
      - lint
      - unit-tests
      - e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Dodaj komentarz do PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              console.log('Brak pull requesta');
              return;
            }
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: pr.number,
              body: '✅ Wszystkie zadania w pipeline przeszły pomyślnie.'
            });
